### ISSUE TITLE
Automatic DTED download should be an option

### ISSUE THREAD

**Issue by FarrantAlex** [deptofdefense/AndroidTacticalAssaultKit-CIV#249]
## takv
ATAK-CIV:4.7.0.0 (2630c526)[playstore].1658845578-CIV

## Issue
Automatic DTED download is using a lot of bandwidth without warning. 
Unlike map layers, the user has no control over this other than DNS blocking tak.gov.
```
09-03 18:20:49.537 13720 23240 W ElevationDownloader: Failed to download tile https://tak.gov/elevation/DTED/w002/n51.dt0.zip
09-03 18:20:49.537 13720 23240 W ElevationDownloader: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:1450)
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:1399)
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:1343)
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:221)
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
09-03 18:20:49.537 13720 23240 W ElevationDownloader: 	at com.atakmap.android.elev.b$5.run(SourceFile:506)
```

## Recommendation
Make automatic DTED downloading a user preference to avoid wasting bandwidth or mobile data.

**Comment by FarrantAlex** [comment]
Some transparency re this feature would be welcome too. The biggest gripe on app store reviews is privacy yet the app is making requests to a .gov domain when a user pans the map - but this isn't mentioned AFAIK.

**Comment by bisgroves** [comment]
It is an option and can be disabled as part of settings or you can point to your own private elevation source.

**Comment by FarrantAlex** [comment]
Noted. Thanks for responding.
