### ISSUE TITLE
JNI crash when loading a 3D Tiles dataset.

### ISSUE THREAD

**Issue by algostrat** [deptofdefense/AndroidTacticalAssaultKit-CIV#333]
An exception is thrown when zooming into the dataset after loading and selecting it in the overlays menu. 
[aircraft-carrier.zip](https://github.com/user-attachments/files/18014082/aircraft-carrier.zip). The tileset is just one b3dm model located near the golden gate bridge. 

I've tried other datasets using gltf and .3tz and the same exception is thrown. This is happening on ATAK-5.3.0.4-a0a821fa-civ-release.apk. 

The device is a samsung tab s7.

`
java.lang.UnsatisfiedLinkError: No implementation found for boolean com.atakmap.map.formats.c3dt.n.intersects(long, double, double, double, double) (tried Java_com_atakmap_map_formats_c3dt_n_intersects and Java_com_atakmap_map_formats_c3dt_n_intersects__JDDDD)
                                                                                                    	at com.atakmap.map.formats.c3dt.n.intersects(Native Method)
                                                                                                    	at com.atakmap.map.formats.c3dt.n.a(SourceFile:725)
                                                                                                    	at com.atakmap.map.formats.c3dt.n.a(SourceFile:279)
                                                                                                    	at com.atakmap.map.formats.c3dt.o.draw(SourceFile:240)
                                                                                                    	at com.atakmap.map.opengl.b.draw(SourceFile:346)
                                                                                                    	at com.atakmap.map.layer.opengl.d.draw(SourceFile:45)
                                                                                                    	at atak.core.np.draw(SourceFile:133)
                                                                                                    	at com.atakmap.map.layer.opengl.f.a(SourceFile:103)
                                                                                                    	at com.atakmap.map.layer.opengl.b.draw(SourceFile:63)
                                                                                                    	at com.atakmap.map.layer.opengl.g.a(SourceFile:148)
                                                                                                    	at com.atakmap.map.layer.opengl.b.draw(SourceFile:63)
                                                                                                    	at com.atakmap.map.layer.opengl.f.a(SourceFile:103)
                                                                                                    	at com.atakmap.map.layer.opengl.b.draw(SourceFile:63)
                                                                                                    	at com.atakmap.map.opengl.GLMapView.render(Native Method)
                                                                                                    	at com.atakmap.map.opengl.GLMapView.render(SourceFile:1370)
                                                                                                    	at com.atakmap.map.opengl.h.onDrawFrame(SourceFile:104)
                                                                                                    	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1593)
                                                                                                    	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1287)
`

**Comment by bisgroves** [comment]
This should now be resolved.

**Comment by algostrat** [comment]
Thanks, crash is no longer happening on ATAK-5.3.0.9-611dc43b-civ-release.apk
