### ISSUE TITLE
Included atak.apk crashes on emulator on startup

### ISSUE THREAD

**Issue by rotinom** [deptofdefense/AndroidTacticalAssaultKit-CIV#48]
Pixel 2 emulator.  x86_64 API 26

**Comment by null0nil** [comment]
You may need to disable hardware OpenGL.

First start the emulator.  Then, from the sidebar, click  the vertical bar "…" icon.

Setting->Advanced:
Under “OpenGL ES renderer”:  Choose  “SwiftShader” 
Under “OpenGL ES API level”:  Choose  “Renderer maximum (up to OpenGL ES 3.1)” 
Then, exit/shut down the emulator.

**Comment by rob-baily** [comment]
I have been what seems to be the same issue.  I was able to attach a debugger and I see this stack trace in the logcat.  If I click the square to see processes it appears ATAK is still at the loading screen.

2022-03-04 14:03:54.786 21582-24695/com.atakmap.app.civ E/FileSystemUtils: soft warning, file name did not pass sanity check: /storage/emulated/0/atak/attachments/ANDROID-BC%3A7F%3AA4%3A0F%3AD2%3A7D/
    java.lang.Exception
        at com.atakmap.coremap.filesystem.FileSystemUtils.sanitizeWithSpacesAndSlashes(SourceFile:1032)
        at com.atakmap.android.util.AttachmentManager.getFolderPath(SourceFile:377)
        at com.atakmap.android.util.AttachmentManager.getFolderPath(SourceFile:401)
        at com.atakmap.android.attachment.AttachmentBroadcastReceiver.onMapEvent(SourceFile:91)
        at com.atakmap.android.maps.MapEventDispatcher.dispatch(SourceFile:280)
        at com.atakmap.android.maps.MapGroupItemsChangedEventForwarder.onItemRemoved(SourceFile:45)
        at com.atakmap.android.maps.MapGroup.dispatchItemRemoved(SourceFile:649)
        at com.atakmap.android.maps.MapGroup.removeItem(SourceFile:731)
        at com.atakmap.android.maps.MapItem.removeFromGroup(SourceFile:699)
        at com.atakmap.android.cot.CotMarkerRefresher.checkStaleTeams(SourceFile:285)
        at com.atakmap.android.cot.CotMapComponent$8.run(SourceFile:665)
        at java.util.TimerThread.mainLoop(Timer.java:562)
        at java.util.TimerThread.run(Timer.java:512)

**Comment by ayeseeem** [comment]
> You may need to disable hardware OpenGL.
> 
> First start the emulator. Then, from the sidebar, click on the vertical bar "…" icon.
> 
> Setting->Advanced: Under “OpenGL ES renderer”: Choose “SwiftShader” Under “OpenGL ES API level”: Choose “Renderer maximum (up to OpenGL ES 3.1)” Then, exit/shut down the emulator.

I don't know how you discovered this, or who else needs to know, but this saved me when trying to resurrect an old project, with ATAK v4.9, Android Studio Flamingo | 2022.2.1 Patch 2, and emulating Pixel C API 34 and Pixel 3a API 34.

In fact, I only needed the second part - just the "Renderer maximum (up to OpenGL ES 3.1)".

**Comment by mohdnr** [comment]
i was having this same issue and eventually gaveup when nothing worked. I found this golden tip at the bottom of the ATAK SDK guide and it immediately solved my opengl issue on my apple silicon mac. just note that the `sdcard/atak` path won't exist until atak has been launched atleast once.

```powershell
cd C:\Users\%USERNAME%\AppData\Local\Android\Sdk\platform-tools
adb.exe shell
cd sdcard/atak/
touch opengl.broken
exit
```
```bash
cd /Users/${USER}/Library/Android/sdk/platform-tools
adb shell
cd sdcard/atak/
touch opengl.broken
exit
```

**Comment by coyotespike** [comment]
Thanks @mohdnr, that worked!

Also running Android emulator on M1 Mac, having run a simple `adb install atak.apk`, granted permissions, chose to delete the nonexistent encrypted db and gave a new secret passphrase, the app kept crashing.

I tried monkeying with OpenGL renderer (both command line and as helpfully advised above) but that didn't work.

After creating `opengl.broken` the app finally did not crash on reopen.

Worth noting that this instruction is on the last page of the ATAK plugin structure guide, but explicit commands are helpful 😄
